const ITINERARIES_DB = [
  {
    id: "tavolara_pro",
    title: "Il Regno di Tavolara & Molara",
    dist: "14nm",
    time: "55min",
    fuel: "45-60€",
    wind: "Ovest/Nord-Ovest",
    difficulty: "Facile",
    color: "#00b4d8",
    stops: [
      {
        name: "Cala Moresca",
        time: "10m",
        lat: "40.993",
        lng: "9.623",
        tip: "Perfetta al mattino",
      },
      {
        name: "Piscine di Molara",
        time: "+25m",
        lat: "40.871",
        lng: "9.708",
        tip: "Acqua color cristallo",
      },
      {
        name: "Spalmatore (Tavolara)",
        time: "+15m",
        lat: "40.887",
        lng: "9.686",
        tip: "Pranzo al Re di Tavolara",
      },
    ],
  },
  {
    id: "costa_smeralda",
    title: "Costa Smeralda & Exclusive Bays",
    dist: "22nm",
    time: "80min",
    fuel: "80-110€",
    wind: "Sud/Est",
    difficulty: "Media",
    color: "#2ecc71",
    stops: [
      {
        name: "Cala di Volpe",
        time: "35m",
        lat: "41.036",
        lng: "9.538",
        tip: "Guarda gli Yacht VIP",
      },
      {
        name: "Spiaggia del Principe",
        time: "+15m",
        lat: "41.047",
        lng: "9.554",
        tip: "La più bella della Costa",
      },
      {
        name: "Isola di Soffi",
        time: "+20m",
        lat: "41.052",
        lng: "9.519",
        tip: "Piscine naturali",
      },
    ],
  },
  {
    id: "capo_figari",
    title: "Wild Capo Figari & Delfini",
    dist: "6nm",
    time: "20min",
    fuel: "20-30€",
    wind: "Tutti i venti",
    difficulty: "Principiante",
    color: "#f1c40f",
    stops: [
      {
        name: "Cala Greca",
        time: "15m",
        lat: "40.999",
        lng: "9.635",
        tip: "Scogliere a picco",
      },
      {
        name: "Isolotto di Figarolo",
        time: "+10m",
        lat: "40.983",
        lng: "9.620",
        tip: "Avvistamento Delfini",
      },
    ],
  },
  {
    id: "mortorio_island",
    title: "Arcipelago di Mortorio (Incontaminato)",
    dist: "18nm",
    time: "65min",
    fuel: "65-90€",
    wind: "Ovest",
    difficulty: "Media",
    color: "#9b59b6",
    stops: [
      {
        name: "Isola di Mortorio",
        time: "50m",
        lat: "41.082",
        lng: "9.564",
        tip: "Riserva Naturale Integrale",
      },
      {
        name: "Cala Petra Ruja",
        time: "+15m",
        lat: "41.026",
        lng: "9.529",
        tip: "Spiaggia rossa selvaggia",
      },
    ],
  },
  {
    id: "porto_rotondo",
    title: "Porto Rotondo & Punta Volpe",
    dist: "10nm",
    time: "35min",
    fuel: "35-50€",
    wind: "Nord-Est",
    difficulty: "Facile",
    color: "#e67e22",
    stops: [
      {
        name: "Spiaggia Ira",
        time: "30m",
        lat: "41.030",
        lng: "9.520",
        tip: "Sabbia bianca finissima",
      },
      {
        name: "Punta Volpe",
        time: "+10m",
        lat: "41.035",
        lng: "9.542",
        tip: "Ottimo per snorkeling",
      },
    ],
  },
];

/**
 *
 * 1. CONFIGURAZIONE E STATO
 */
const CONFIG = {
  months: [
    "Gennaio",
    "Febbraio",
    "Marzo",
    "Aprile",
    "Maggio",
    "Giugno",
    "Luglio",
    "Agosto",
    "Settembre",
    "Ottobre",
    "Novembre",
    "Dicembre",
  ],
  days: ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
  basePrices: [150, 200, 130, 180, 250],
  multipliers: { 4: 1.0, 5: 1.2, 6: 1.5, 7: 1.8, 8: 1.2 },
  allExtras: [
    "Ghiacciaia",
    "Telo e crema solare",
    "Kit snorkeling",
    "Giochi gonfiabili",
    "Set GoPro",
    "Benzina",
  ],
};